---
- name: Web server configuration playbook
  hosts: webservers
  tasks:
    - name: Update the system packages # sudo apt update
      apt:
        update_cache: yes
      become: yes

    - name: Restart Nginx (non-critical task)
      service:
        name: nginx
        state: restarted # present, started
      ignore_errors: yes
      become: yes

    - name: Update firewall rules to allow HTTP and HTTPS traffic
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 80   # HTTP
        - 443  # HTTPS
      become: yes
